#!/bin/bash

index=1

container_list=`docker ps --format '{{.ID}}'`
count=`echo -e "$container_list" | wc -l`

if [ "$container_list" == '' ];then
    echo "No running containers found."
    exit 1
fi

while read -r id; do
    docker kill $id
done <<< "$container_list"