#!/bin/bash

index=${1}

container_list=`docker ps --format '{{.Names}}\t{{.ID}}'`
count=`echo -e "$container_list" | wc -l`

if [ "$container_list" == '' ];then
    echo "No running containers found."
    exit 1
fi

if [[ $index -ne "" ]]; then
# Index has been already set
echo "Using index $index"
elif [ $count -eq 1 ];then
index=1
elif [ $count -gt 1 ];then
    x=0
    echo Which container?
    while read -r line; do
        x=$((x+1))
        container_name=$(echo "$line" | awk '{ print $1 }')
        echo "[$x] $container_name"
    done <<< "$container_list"
    read index
fi

if ! [[ $index =~ ^-?[0-9]+$ ]];then echo "Error: $index is not a number" >&2; exit 1; fi
if [[ "$index" -lt 1 ]] || [[ "$index" -gt $count ]]; then echo "Error: $index not in range [1-$(echo $count)]" >&2; exit 1; fi

container=$(echo "$container_list" | sed -n "$index p" | awk '{ print $1 }' )

docker exec -ti $container bash

if [ "$?" -ne 0 ]; then
    echo "Login failed, trying sh"
    docker exec -ti $container sh
fi
